In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
df = pd.read_csv('movie_data.csv')

In [4]:
df.head(10)

,index,movie-link-href,original_title,overview,popularity,production_companies,release_date,runtime,spoken_languages,cast,director,writers,vote_average,vote_counts,keywords,genre,revenue,budget
0,0,https://www.imdb.com/title/tt0119217/?ref_=adv...,Good Will Hunting,"Will Hunting, a janitor at M.I.T., has a gift ...",299.0,Miramax Be Gentlemen Limited Partnership Lawre...,"January 9, 1998 (United States)",2 hours 6 minutes,English,Robin Williams Matt Damon Ben Affleck John Mig...,Gus Van Sant,Matt Damon Ben Affleck,8.3,948334,professor genius friend janitor character name...,Drama Romance,"$225,933,435","$10,000,000 (estimated)"
1,1,https://www.imdb.com/title/tt0118715/?ref_=adv...,The Big Lebowski,"Ultimate L.A. slacker Jeff ""The Dude"" Lebowski...",491.0,Polygram Filmed Entertainment Working Title Films,"March 6, 1998 (United States)",1 hour 57 minutes,English German Hebrew Spanish,Jeff Bridges John Goodman Julianne Moore Steve...,Joel Coen,Ethan Coen Ethan Coen Joel Coen,8.1,797497,rug nihilism death of friend bowling alley cul...,Comedy Crime,"$46,969,409","$15,000,000 (estimated)"
2,2,https://www.imdb.com/title/tt0371746/?ref_=adv...,Iron Man,"After being held captive in an Afghan cave, bi...",295.0,Paramount Pictures Marvel Enterprises Marvel S...,"May 2, 2008 (United States)",2 hours 6 minutes,English Persian Urdu Arabic Kurdish Hindi Hung...,Gwyneth Paltrow Terrence Howard Jeff Bridges L...,Jon Favreau,Writers Mark Fergus Hawk Ostby Art Marcum,7.9,1039743,billionaire inventor marvel cinematic universe...,Action Adventure,"$585,796,247","$140,000,000 (estimated)"
3,3,https://www.imdb.com/title/tt0443680/?ref_=adv...,The Assassination of Jesse James by the Coward...,"Robert Ford, who's idolized Jesse James since ...",1725.0,Scott Free Productions,"October 19, 2007 (United States)",2 hours 40 minutes,English Danish,Brad Pitt Casey Affleck Sam Shepard Brooklynn ...,Andrew Dominik,Andrew Dominik Ron Hansen,7.5,180268,betrayal idol long title assassination based o...,Biography Crime Drama History Western,"$15,001,776","$30,000,000 (estimated)"
4,4,https://www.imdb.com/title/tt0783233/?ref_=adv...,Atonement,Thirteen-year-old fledgling writer Briony Tall...,634.0,Universal Pictures StudioCanal Relativity Media,"January 11, 2008 (United States)",2 hours 3 minutes,English French,Keira Knightley James McAvoy Brenda Blethyn Sa...,Joe Wright,Ian McEwan Christopher Hampton,7.8,275108,world war two rape loss of virginity miscarria...,Drama Mystery Romance,"$131,016,624","$30,000,000 (estimated)"
5,5,https://www.imdb.com/title/tt0993842/?ref_=adv...,Hanna,A sixteen-year-old girl who was raised by her ...,3160.0,Focus Features Holleran Company Sechzehnte Bab...,"April 8, 2011 (United States)",1 hour 51 minutes,English French German Italian Arabic Spanish,Saoirse Ronan Cate Blanchett Eric Bana Vicky K...,Joe Wright,Seth Lochhead David Farr,6.8,198444,action heroine pistol revenge rogue agent titl...,Action Adventure Drama,"$63,782,078","$30,000,000 (estimated)"
6,6,https://www.imdb.com/title/tt0432348/?ref_=adv...,Saw II,A detective and his team must rescue 8 people ...,3691.0,Twisted Pictures Evolution Entertainment Got F...,"October 28, 2005 (United States)",1 hour 33 minutes,English,Donnie Wahlberg Beverley Mitchell Franky G Emm...,Darren Lynn Bousman,Leigh Whannell Darren Lynn Bousman,6.6,250430,serial killer vcr police officer game of death...,Horror Mystery,"$147,748,505","$4,000,000 (estimated)"
7,7,https://www.imdb.com/title/tt0415306/?ref_=adv...,Talladega Nights: The Ballad of Ricky Bobby,Number one NASCAR driver Ricky Bobby stays ato...,833.0,Columbia Pictures Relativity Media Apatow Prod...,"August 4, 2006 (United States)",1 hour 48 minutes,English French,Will Ferrell Sacha Baron Cohen Gary Cole Micha...,Adam McKay,Will Ferrell Adam McKay,6.6,183500,motor sports race car driver winner takes all ...,Comedy Sport,"$163,362,095","$72,500,000 (estimated)"
8,8,https://www.imdb.com/title/tt1454029/?ref_=adv...,The Help,An aspiring author during the civil rights mov...,706.0,DreamWorks Dreamworks Pictures,"August 10, 2011 (United States)",2 hours 26 minutes,English,Emma Stone Viola Davis Octavia Spencer Bryce D...,Tate Taylor,Tate Taylor Kathryn Stockett,8.1,453989,chocolate pie writer newspaper columnist expec...,Drama,"$216,639,112","$25,000,000 (estimated)"
9,9,https://www.imdb.com/title/tt1646987/?ref_=adv...,Wrath of the Titans,Perseus braves the treacherous underworld to r...,4721.0,Legendary Entertainment Cott Productions,"March 30, 2012 (United States)",1 hour 39 minutes,English,Sam Worthington Liam Neeson Rosamund Pike Ralp...,Jonathan Liebesman,Writers Dan Mazeau Greg Berlanti,5.7,188889,greek mythology underworld poseidon character ...,Action Adventure Fantasy,"$301,970,083","$150,000,000 (estimated)"

In [5]:
df.describe()

             index    popularity  vote_average   vote_counts
count  8586.000000   8585.000000   8586.000000  8.586000e+03
mean   4292.500000   6824.890740      6.495993  9.547991e+04
std    2478.709039   5903.682763      0.973856  1.696990e+05
min       0.000000      1.000000      1.200000  9.705000e+03
25%    2146.250000   2583.000000      5.900000  1.756450e+04
50%    4292.500000   5429.000000      6.600000  3.701050e+04
75%    6438.750000   9391.000000      7.200000  9.694175e+04
max    8585.000000  74243.000000      9.300000  2.619098e+06

In [6]:
df.columns

Index(['index', 'movie-link-href', 'original_title', 'overview', 'popularity',
       'production_companies', 'release_date', 'runtime', 'spoken_languages',
       'cast', 'director', 'writers', 'vote_average', 'vote_counts',
       'keywords', 'genre', 'revenue', 'budget'],
      dtype='object')

In [7]:
df.count()

index                   8586
movie-link-href         8586
original_title          8586
overview                8586
popularity              8585
production_companies    8225
release_date            8586
runtime                 8586
spoken_languages        8586
cast                    8584
director                8585
writers                 8319
vote_average            8586
vote_counts             8586
keywords                8586
genre                   8586
revenue                 7622
budget                  6573
dtype: int64

In [8]:
df.drop(columns=['budget','revenue'],inplace=True)

In [9]:
df.columns

Index(['index', 'movie-link-href', 'original_title', 'overview', 'popularity',
       'production_companies', 'release_date', 'runtime', 'spoken_languages',
       'cast', 'director', 'writers', 'vote_average', 'vote_counts',
       'keywords', 'genre'],
      dtype='object')

In [10]:
df.drop(columns=['movie-link-href'],inplace=True)

In [11]:
df.head()

,index,original_title,overview,popularity,production_companies,release_date,runtime,spoken_languages,cast,director,writers,vote_average,vote_counts,keywords,genre
0,0,Good Will Hunting,"Will Hunting, a janitor at M.I.T., has a gift ...",299.0,Miramax Be Gentlemen Limited Partnership Lawre...,"January 9, 1998 (United States)",2 hours 6 minutes,English,Robin Williams Matt Damon Ben Affleck John Mig...,Gus Van Sant,Matt Damon Ben Affleck,8.3,948334,professor genius friend janitor character name...,Drama Romance
1,1,The Big Lebowski,"Ultimate L.A. slacker Jeff ""The Dude"" Lebowski...",491.0,Polygram Filmed Entertainment Working Title Films,"March 6, 1998 (United States)",1 hour 57 minutes,English German Hebrew Spanish,Jeff Bridges John Goodman Julianne Moore Steve...,Joel Coen,Ethan Coen Ethan Coen Joel Coen,8.1,797497,rug nihilism death of friend bowling alley cul...,Comedy Crime
2,2,Iron Man,"After being held captive in an Afghan cave, bi...",295.0,Paramount Pictures Marvel Enterprises Marvel S...,"May 2, 2008 (United States)",2 hours 6 minutes,English Persian Urdu Arabic Kurdish Hindi Hung...,Gwyneth Paltrow Terrence Howard Jeff Bridges L...,Jon Favreau,Writers Mark Fergus Hawk Ostby Art Marcum,7.9,1039743,billionaire inventor marvel cinematic universe...,Action Adventure
3,3,The Assassination of Jesse James by the Coward...,"Robert Ford, who's idolized Jesse James since ...",1725.0,Scott Free Productions,"October 19, 2007 (United States)",2 hours 40 minutes,English Danish,Brad Pitt Casey Affleck Sam Shepard Brooklynn ...,Andrew Dominik,Andrew Dominik Ron Hansen,7.5,180268,betrayal idol long title assassination based o...,Biography Crime Drama History Western
4,4,Atonement,Thirteen-year-old fledgling writer Briony Tall...,634.0,Universal Pictures StudioCanal Relativity Media,"January 11, 2008 (United States)",2 hours 3 minutes,English French,Keira Knightley James McAvoy Brenda Blethyn Sa...,Joe Wright,Ian McEwan Christopher Hampton,7.8,275108,world war two rape loss of virginity miscarria...,Drama Mystery Romance

In [12]:
df.rename(columns = {'genre':'genres'}, inplace = True)

In [13]:
df.columns

Index(['index', 'original_title', 'overview', 'popularity',
       'production_companies', 'release_date', 'runtime', 'spoken_languages',
       'cast', 'director', 'writers', 'vote_average', 'vote_counts',
       'keywords', 'genres'],
      dtype='object')

In [14]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [15]:
features = ['cast','genres','director','overview','keywords']

In [16]:
for feature in features:
    df[feature] = df[feature].fillna('')

In [17]:
def combine_features(row):
    return row['keywords'] +' '+row['cast']+' '+row['genres']+' '+row['director']+' '+row['overview']

df['combine_features'] = df.apply(combine_features,axis=1)

print(df['combine_features'].head())

0    professor genius friend janitor character name...
1    rug nihilism death of friend bowling alley cul...
2    billionaire inventor marvel cinematic universe...
3    betrayal idol long title assassination based o...
4    world war two rape loss of virginity miscarria...
Name: combine_features, dtype: object

In [18]:
tfv = TfidfVectorizer(min_df=3, max_df = 700,ngram_range=(1,2),stop_words='english')

In [19]:
tfv_matrix = tfv.fit_transform(df['combine_features'])
cosine_sim = cosine_similarity(tfv_matrix)

In [20]:
def get_index_from_title(title):
    return df[df.original_title == title]['index'].values[0]

def get_title_from_index(index):
    return df[df.index == index]['original_title'].values[0]

In [21]:
def give_rec(movie_recommended):
    movie_index = get_index_from_title(movie_recommended)
    similar_movies = list(enumerate(cosine_sim[movie_index]))
    sorted_similar_movies = sorted(similar_movies,key=lambda x:x[1],reverse=True)
    
    i = 0
    for movie in sorted_similar_movies:
        print(get_title_from_index(movie[0]))
        i = i+1
        if i>5:
            break

In [22]:
give_rec('Tenet')

Tenet
Interstellar
The 355
Predestination
The Man from U.N.C.L.E.
Mission: Impossible - Fallout

In [24]:
give_rec('Cast Away')

Cast Away
Six Days Seven Nights
Lord of the Flies
Nim's Island
The Blue Lagoon
The Most Dangerous Game

In [25]:
give_rec('2001: Space Odyssey')

IndexError: index 0 is out of bounds for axis 0 with size 0